### ISSUE TITLE
Containers logging us into the incorrect container no matter which container is selected 

### ISSUE THREAD

**Issue by marianafalcho** [tedsmitt/ecsgo#20]
Hello there!

We are having a weird issue using `ecsgo`. Every time we run the tool and we select a particular container, it logs us into a different one, never to the main container. (In the example below it logs me into the logger container)
Per the instructions in your README, I checked the the ssm plugin and the permissions setup for each task. Everything looks good.

I even a run a tool to validate if the `ecs exec command` and I got the results below.

<img width="1101" alt="Screen Shot 2022-10-12 at 4 58 36 PM" src="https://user-images.githubusercontent.com/79718990/195718615-96d5ebc3-3765-44d3-95fb-7e7abf01b26d.png">

**Comment by tedsmitt** [comment]
Thank you so much for raising this issue! I'll look into this asap 🙂

**Comment by marianafalcho** [comment]
Hi @tedsmitt,
Please review #22 for possible solution to this ticket. 

Thank you !

**Comment by tedsmitt** [comment]
Thanks @marianafalcho for raising this issue and thank you @yerfinojul for providing a fix!
