### ISSUE TITLE
List services operation not paginated

### ISSUE THREAD

**Issue by j-boivie** [tedsmitt/ecsgo#23]
👋 

As mentioned in #21 I noticed that the output when fetching all services on a cluster isn't paginated here: https://github.com/tedsmitt/ecsgo/blob/95178ae50b5d102c5ffea4eb3f5723c6fad40353/internal/exec.go#L124-L125
This causes missing services in the output if you run more than 10 services on a single cluster. 

I also looked a bit further in the code and noticed that the same seems to be true when fetching tasks, although if I read the documentation right the `ListTasks` call seems to return 100 tasks in a single page, so that might not be as much of an issue.

I'd be willing to submit a patch for this, but I can't really say when I'll have the time to do it right now 🙈

**Comment by tedsmitt** [comment]
Hey @j-boivie I've added this in https://github.com/tedsmitt/ecsgo/releases/tag/0.4.5-beta.1 - can you check it out and feedback? Cheers
