### ISSUE TITLE
Non-interactive task selection

### ISSUE THREAD

**Issue by morph027** [tedsmitt/ecsgo#28]
Just an idea. Would it be possible to supply cluster, service and taskid via commandline to directly connect to the container without the interactive menu?

e.g.:

```
ecsgo --profile <profile> --cmd bash --cluster <cluster> --service <service> --task <task>
```

Merry christmas 😉

**Comment by tedsmitt** [comment]
Hey @morph027 I've added this and released in https://github.com/tedsmitt/ecsgo/releases/tag/0.4.5-beta.1 - could you check it out and feedback?

**Comment by morph027** [comment]
Hi. Wow, thanks. Jip, will try later.

**Comment by morph027** [comment]
Tested and can confirm it works, awesome!

**Comment by morph027** [comment]
Just noticed that `-u, --container string`lists `Task ID`as help. Should be something like `Container name`.

**Comment by tedsmitt** [comment]
Thanks @morph027 for spotting that! Good eye! Have just pushed a commit that fixes that, and will be rolled out in the upcoming release!
