### ISSUE TITLE
Connecting to incorrect container

### ISSUE THREAD

**Issue by mikeforkin** [tedsmitt/ecsgo#53]
I've just downloaded 0.6.0 and I'm trying to connect to a container, however, it is connecting to a different container than the one I selected. I've tried to debug locally, but I cannot replicate the issue as any local builds work just fine. 

I am on an intel mac running Ventura 13.6.7.

**Comment by mikeforkin** [comment]
If it helps at all, it is always picking the same container (the last one in the list) to log into rather than the one that I selected.

**Comment by tedsmitt** [comment]
Thanks for raising @mikeforkin, I'll try and find some time to look into this tomorrow.

**Comment by tedsmitt** [comment]
@mikeforkin Thanks for reporting this, that was a pretty gnarly bug! Fixed in https://github.com/tedsmitt/ecsgo/releases/tag/v0.6.1

**Comment by tedsmitt** [comment]
Re-released [v0.6.1](https://github.com/tedsmitt/ecsgo/releases/tag/v0.6.1)

**Comment by mikeforkin** [comment]
> @mikeforkin Thanks for reporting this, that was a pretty gnarly bug! Fixed in [v0.6.1](https://github.com/tedsmitt/ecsgo/releases/tag/v0.6.1)
> 
> EDIT: I've fixed the Task selection but not the container selection! d'oh! I will re-release v0.6.1 shortly

 Awesome, thanks for looking into it!
